// frontend/src/MenuItem.vue
<template>
  <li>
    <h3 :class="{ clickable: item.folder }" @click="onSelect">
      {{ item.title }}
    </h3>
    <ul v-if="item.sub_chapters && item.sub_chapters.length > 0">
      <menu-item
        v-for="item in item.sub_chapters"
        :key="item.title"
        :item="item"
      >
      </menu-item>
    </ul>
  </li>
</template>
  
<script>
export default {
  name: "MenuItem",
  components: {},
  props: {
    item: Object,
  },
  data: function () {
    return {};
  },
  mounted: async function () {},
  methods: {
    onSelect: function () {
        console.log("clicked ==")
        this.eventBus.emit("load", this.item);
      
    },
  },
};
</script>
  
<style>
.clickable {
  cursor: pointer;
}

.clickable:hover {
  background-color: red;
}
</style>

// frontend/src/MenuItem.jsx
import { createSignal } from 'solid-js'
import styles from './MenuItem.module.css'

function MenuItem(props) {
    function onSelect(e) {
        props.load(props.item);
    }
    return (
        <li class={`${styles.MenuItem} ${styles.ClickableItem}`} >
            <h3 classList={{menutitle:true, clickable: props.item.folder }} onClick={onSelect}>
                {props.item.title}
            </h3>
            <Show when={props.item.sub_chapters && props.item.sub_chapters.length > 0}>
                <ul>
                    <For each={props.item.sub_chapters}>
                        {(item, i) =>
                            <MenuItem
                                key={item.title}
                                item={item}
                                load={props.load}
                                >
                            </MenuItem>}
                    </For>
                </ul>
            </Show>
        </li >
    )
}

export default MenuItem
